#!/bin/bash
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DEPLOY_TARGET="zinc@192.168.68.73"
DEPLOY_REMOTE_DIR="/home/zinc/yt-plex-mini"
IMAGE="ghcr.io/zincplusplus/yt-plex:latest"

echo "Deploying to $DEPLOY_TARGET:$DEPLOY_REMOTE_DIR..."
ssh "$DEPLOY_TARGET" "find $DEPLOY_REMOTE_DIR -mindepth 1 -not -path '*/data/*' -not -path '*/downloads/*' -not -name '.env' -delete 2>/dev/null; mkdir -p $DEPLOY_REMOTE_DIR"
rsync -av --exclude='data/' --exclude='downloads/' --exclude='.venv/' --exclude='__pycache__/' --exclude='.git/' --exclude='.DS_Store' --exclude='.env' "$SCRIPT_DIR/" "$DEPLOY_TARGET:$DEPLOY_REMOTE_DIR/"
echo "Creating data backups on remote..."
ssh "$DEPLOY_TARGET" "cd $DEPLOY_REMOTE_DIR && mkdir -p data/backups && ts=\$(date +%Y%m%d_%H%M%S); [ -f data/queue.db ] && cp data/queue.db data/backups/queue.db.\$ts.bak || true; [ -f data/settings.json ] && cp data/settings.json data/backups/settings.json.\$ts.bak || true; [ -f data/sources.json ] && cp data/sources.json data/backups/sources.json.\$ts.bak || true"
echo "Building and pushing image..."
ssh "$DEPLOY_TARGET" "cd $DEPLOY_REMOTE_DIR && DOCKER_BUILDKIT=1 docker build -t $IMAGE . && docker push $IMAGE"
echo "Restarting containers..."
ssh "$DEPLOY_TARGET" "cd $DEPLOY_REMOTE_DIR && docker compose down && docker compose up -d"
echo "Done."
